### ISSUE TITLE
国际化除了示例代码中的设置Intl.defaultLocale = local，是否还有其他配置方式？

### ISSUE THREAD

**Issue by e4ky** [evansherry/dh_picker#1]
有自己的手机中当前语言配置是zh，，在Main中未对Intl.defaultLocale做配置，时间选择对话框还是显示Done和Cancel，是否有类似于此类设置方式？
![image](https://github.com/evanwsu/dh_picker/assets/11674702/59da9fa4-cf9e-4ebd-b19c-7e0829690621)

**Comment by evanwsu** [comment]
没有，多语言文本建议从外部传入
